package com.alaeldin.Auth_service.dto;

import com.fasterxml.jackson.annotation.JsonSetter;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.extern.jackson.Jacksonized;

/**
 * Request payload for the user registration endpoint.
 *
 * <p>All fields are validated via Bean Validation (JSR-380) before the request
 * reaches the service layer. Constraints are intentionally aligned with the
 * {@link com.alaeldin.Auth_service.model.User} entity column definitions so
 * that validation failures are caught at the API boundary, not at the database.</p>
 *
 * <p>This class automatically trims whitespace from username, email, and password
 * during deserialization to prevent registration failures from accidental
 * leading or trailing spaces (a common user error when copy-pasting credentials).</p>
 */
@Getter
@Builder
@Jacksonized
@AllArgsConstructor
@NoArgsConstructor
public class RegisterRequest {

    /**
     * Unique login handle for the new user.
     *
     * <ul>
     *   <li>Must not be blank.</li>
     *   <li>Between 3 and 50 characters (matches {@code users.Firstname} column length).</li>
     *   <li>Only letters, digits, and underscores — no spaces or special characters.</li>
     *   <li>Automatically trimmed during deserialization.</li>
     * </ul>
     */
    @NotBlank(message = "First Name is required")
    @Size(min = 3, max = 50, message = "First Name must be between 3 and 50 characters")
    @Pattern(
            regexp  = "^[a-zA-Z0-9_]+$",
            message = "First Name must contain only letters, digits, and underscores"
    )
    private String firstName;

    /**
     * <ul>
     *   <li> Between 3 And 50 characters</li>
     *   <li>Only Letters , Digits ,and underscores — no spaces or special characters.</li>
     * </ul>
     */
    @Size(min = 3 , max = 50 , message = "Middle Name Must be Between 3 And 50 Characters")
    @Pattern(regexp ="^[a-zA-Z0-9_]+$",
    message = "Middle  Name must Contains Only Letters , digits , and underScore")
    private String middleName;

    /**
     * <ul>
     *  <li> Not Blank </li>
     *  <li> Between  3 to 50 Characters </li>
     *  <li> Only Letters , Digits , And UndersCores</li>
     * </ul>
     */
    @NotBlank(message = "Last Name Is Required")
    @Size(min = 3 , max = 50 , message = "Last Name must be between 3 to 50 Characters")
    @Pattern(regexp = "^[a-zA-Z0-9_]+$" , message = "Middle Name must Contain  Only  Letters , digits , And underscores ")
    private String lastName;

    /**
     * Unique email address for the new user.
     *
     * <ul>
     *   <li>Must not be blank.</li>
     *   <li>Must be a well-formed RFC 5322 email address.</li>
     *   <li>Must not exceed 100 characters (matches {@code users.email} column length).</li>
     *   <li>Automatically trimmed during deserialization.</li>
     * </ul>
     */
    @NotBlank(message = "Email is required")
    @Email(message = "Must be a valid email address")
    @Size(max = 100, message = "Email must not exceed 100 characters")
    private String email;

    /**
     * <ul>
     *    <li>Not Blank</li>
     *    <li>Between 10 to 14 Numbers</li>
     *    <li>Only Number And (+) Like this +971588530119</li>
     * </ul>
     */
    @NotBlank(message = "Phone Number is required")
    @Pattern(regexp = "^\\+?[0-9]{10,14}$",
            message = "Phone Number Must be Number And (+) ")
    private String phone;

    /**
     * National ID of the user.
     * 
     * <ul>
     *   <li>Must be between 10 and 20 characters</li>
     *   <li>Can contain digits, letters, underscores, and hyphens</li>
     *   <li>Used as part of the identity file naming</li>
     * </ul>
     */
    @NotBlank(message = "National Id Is Required")
    @Size(min = 10, max = 20, message = "National Id must be between 10 and 20 characters")
    @Pattern(regexp = "^[a-zA-Z0-9_-]+$", message = "National Id can only contain letters, numbers, underscores, and hyphens")
    private String nationalId;

    /**
     * Identity file path where the uploaded document will be stored.
     * 
     * <p>This field is auto-generated by the server after file upload.
     * Leave empty or null in the request - it will be populated automatically.</p>
     */
    private String identityFilePath;

    /**
     * Plain-text password chosen by the user.
     *
     * <p><strong>Never log or persist this value.</strong> The service layer is
     * responsible for hashing it (BCrypt / Argon2) before storing in
     * {@code users.password_hash}.</p>
     *
     * <ul>
     *   <li>Must not be blank.</li>
     *   <li>At least 8 characters long.</li>
     *   <li>Must contain at least one uppercase letter, one lowercase letter,
     *       one digit, and one special character ({@code @$!%*?&}).</li>
     *   <li>Automatically trimmed during deserialization.</li>
     * </ul>
     */
    @NotBlank(message = "Password is required")
    @Size(min = 8, message = "Password must be at least 8 characters long")
    @Pattern(
            regexp  = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&]).+$",
            message = "Password must contain at least one uppercase letter, one lowercase letter, one digit, and one special character (@$!%*?&)"
    )
    private String password;

    /**
     * Custom setter for email that trims whitespace.
     * This prevents registration failures from accidental spaces.
     *
     * @param email the raw email from the JSON request
     */
    @JsonSetter("email")
    public void setEmail(String email) {
        this.email = email != null ? email.trim() : null;
    }

    /**
     * Custom setter for password that trims whitespace.
     * This prevents registration failures from accidental spaces.
     *
     * @param password the raw password from the JSON request
     */
    @JsonSetter("password")
    public void setPassword(String password) {
        this.password = password != null ? password.trim() : null;
    }
}
